# Generated by Django 5.2.1 on 2025-05-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HouseHold_Resident", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citizen",
            name="alias",
        ),
        migrations.AddField(
            model_name="citizen",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Nam"), ("female", "Nữ")],
                max_length=10,
                null=True,
            ),
        ),
    ]
