# Generated by Django 5.2.1 on 2025-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHold_Resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='number_people',
            field=models.IntegerField(default=0),
        ),
    ]
