# Generated by Django 5.2.1 on 2025-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHold_Resident', '0002_remove_citizen_alias_citizen_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='job',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='previous_residence',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='workplace',
        ),
        migrations.AddField(
            model_name='citizen',
            name='status',
            field=models.CharField(choices=[('active', 'Đang cư trú'), ('inactive', 'Không cư trú')], default='active', max_length=20),
        ),
    ]
