# Generated by Django 5.2.1 on 2025-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHold_Resident', '0003_remove_citizen_job_remove_citizen_previous_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='status',
            field=models.CharField(choices=[('sinh_song', 'Sinh sống'), ('tam_vang', 'Tạm vắng'), ('tam_tru', 'Tạm trú')], default='sinh_song', max_length=20),
        ),
    ]
