# Generated by Django 4.2 on 2025-05-25 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=11, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("amount", models.PositiveIntegerField()),
                ("unit_code", models.CharField(max_length=50)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "accountant"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["code"], name="Collections_code_742a72_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["unit_code"], name="Collections_unit_co_a932ae_idx"
            ),
        ),
    ]
